---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: debug-statements

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
    - id: autopep8

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
    - id: reorder-python-imports

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      files: src/.*\.py$

- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
    - id: yamllint

# vim: ft=yaml sw=2 ts=2
